[config]

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'

[templates.eza]
input_path = '~/.config/matugen/templates/theme.yml'
output_path = '~/.config/eza/theme.yml'

[templates.fish]
input_path = '~/.config/matugen/templates/fish.theme'
output_path = '~/.config/fish/themes/matugen.theme'
post_hook = "fish -c 'fish_config theme choose matugen'"

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty-theme'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/tokens/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.yatline]
input_path = '~/.config/matugen/templates/yatline-theme.lua'
output_path = '~/.config/yazi/init.lua'
