# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

image {
    monitor =
    path = /home/zvezdari/Pictures/avatar_square.jpg
    rounding = -1
    border_size = 0
    position = 0, 0
}

input-field {
    monitor =
    size = 10%, 3%
    outline_thickness = 3
    dots_spacing = 0.64
    outer_color = rgba(255, 255, 255, 0.6)
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(255, 255, 255, 1)
    font_family = Maple Mono NF CN
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffffa0"><i>Enter Password</i></span>
    rounding = 25
    check_color = rgba(184, 184, 184, 0.5)
    fail_color = rgba(255, 255, 255, 0.6)
    fail_text = <span foreground="##ff6b6b"><i>Authentication Failed</i></span>
    position = 0, -15%
}

# TIME
label {
    monitor =
    text = cmd[update:1000] LC_TIME=en_US.UTF-8 date +'- %-I:%M %p -' | sed 's/./& /g' | sed 's/ $//'
    color = rgba(255, 255, 255, 0.9)
    font_size = 16
    font_family = SF Pro Display, sans-serif
    position = 0, 15%
}

# DATE
label {
    monitor =
    text = cmd[update:60000] LC_TIME=en_US.UTF-8 date +"%A"
    color = rgba(255, 255, 255, 0.9)
    font_size = 84
    font_family = Stange, sans-serif
    position = 0, 25%
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=en_US.UTF-8 date +"%-d %B, %Y" | sed 's/./& /g' | sed 's/ $//'
    color = rgba(255, 255, 255, 0.9)
    font_size = 20
    font_family = SF Pro Display, sans-serif
    position = 0, 19%
}

label {
    monitor =
    text = <i>Zvezdari</i>
    color = rgba(255, 255, 255, 0.9)
    font_size = 16
    font_family = Maple Mono NF CN
    position = 0, -7%
}

label {
    monitor =
    text = <i>Welcome To Arch</i>
    color = rgba(255, 255, 255, 0.9)
    font_size = 16
    font_family = Maple Mono NF CN
    position = 0, -11%
}

# Music progress bar
label {
    monitor =
    text = cmd[update:1000] /home/zvezdari/.config/hypr/music-progress.sh
    font_size = 16
    font_family = Metropolis Medium, Maple Mono NF CN
    color = rgba(255, 255, 255, 0.8)
    position = 0, -25%
}

label {
    monitor =
    text = cmd[update:2000] /bin/bash -c 'artist=$(mpc current -f "%artist%" 2>/dev/null); title=$(mpc current -f "%title%" 2>/dev/null); if [[ -n "$artist" && -n "$title" ]]; then artist_spaced=$(echo " $artist" | sed "s/./& /g"); title_spaced=$(echo "$title " | sed "s/./& /g"); echo "╔══════════════════╗ ║  ${artist_spaced} - ${title_spaced}  ║ ╚══════════════════╝"; else echo "Nothing Playing"; fi'
    font_size = 16
    font_family = Metropolis Medium, Maple Mono NF CN
    color = rgba(255, 255, 255, 0.8)
    position = 0, -30%
}

label {
    monitor =
    text =   Reboot
    color = rgba(255, 255, 255, 0.8)
    font_family = Symbols Nerd Font Mono
    position = -47%, -40%
    onclick = systemctl reboot
}

label {
    monitor =
    text = 󰐥  Poweroff
    color = rgba(255, 255, 255, 0.8)
    font_family = Symbols Nerd Font Mono
    position = -47%, -45%
    onclick = systemctl poweroff
}
